Use metafunc generator
velocyno/AddressBook pull request #26
Opened 2020-08-17 06:27 UTC by amarmulyak

2020-08-19 09:24 UTC, velocyno requested changes

2020-08-19 09:24 UTC, velocyno commented on tests/conftest.py
> +    json_file = open("C:\\Users\\Andrii\\repositories\\AddressBook\\test_input_data\\qa.json")
We should not hardcode the path here
Lets use abspath

2020-08-19 09:24 UTC, velocyno commented on tests/conftest.py
> +        file = open("C:\\Users\\Andrii\\repositories\\AddressBook"
We should not hardcode the path here
Lets use abspath

2020-08-20 10:34 UTC, velocyno requested changes

2020-08-20 10:34 UTC, velocyno commented on tests/test_addresses.py
> +        session_password = "123456"
Why do we use hardcode here?

2020-08-20 10:34 UTC, velocyno commented on tests/test_addresses.py
> +        time.sleep(2)
We use that to wait something?

2020-08-20 10:34 UTC, velocyno commented on tests/test_negative_edit_address.py
> +            # before_all.create_user(browser_fixture)
why we are using commented code on GitHub? :)

2020-08-20 10:34 UTC, velocyno commented on tests/setup/setup_negative_test_add_address.py
> +        cls.file = open("C:\\Users\\Andrii\\repositories\\AddressBook\\test_input_data\\qa.json")
Oops, we have one more hardcode

2020-08-20 10:34 UTC, velocyno commented on conftest.py
> +        # file = open("../test_input_data/qa.json")
commented code on GitHub ? :)

2020-08-20 10:34 UTC, velocyno commented on conftest.py
> +# @pytest.fixture
oops
commented code again

2020-08-25 18:59 UTC, amarmulyak commented on tests/test_addresses.py
> +        session_password = "123456"
These two rows are fixed in "docker" PR

2020-09-13 19:31 UTC, amarmulyak commented on tests/test_addresses.py
> +        session_password = "123456"
Fixed

2020-09-30 12:46 UTC, velocyno approved these changes

2020-09-30 12:46 UTC, merged